# Pre-commit configuration to prevent import issues
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        
  - repo: local
    hooks:
      - id: check-imports
        name: Check for import inconsistencies
        entry: python scripts/check_imports.py
        language: system
        pass_filenames: false
        always_run: true